# Generated by Django 4.2.7 on 2023-12-27 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_passwordmodel_delete_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordmodel',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='passwordmodel',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='passwordmodel',
            name='website_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
