# Generated by Django 4.2.7 on 2024-01-04 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_passwordmodel_last_modified_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passwordmodel',
            options={'verbose_name': 'Password', 'verbose_name_plural': 'Passwords'},
        ),
        migrations.AddField(
            model_name='passwordmodel',
            name='image',
            field=models.ImageField(default=None, upload_to='images/'),
        ),
    ]
