# Generated by Django 4.2.7 on 2024-01-04 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_passwordmodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordmodel',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
