# Generated by Django 4.2.7 on 2024-01-05 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_passwordmodel_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordmodel',
            name='image',
        ),
    ]
