# Generated by Django 4.2.7 on 2024-01-06 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_cardmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardmodel',
            name='card_type',
            field=models.CharField(default=123, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cardmodel',
            name='expiration_date',
            field=models.CharField(max_length=5),
        ),
    ]
