# Generated by Django 4.2.7 on 2024-01-15 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_notemodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notemodel',
            old_name='note_content',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='notemodel',
            old_name='note_title',
            new_name='title',
        ),
    ]
