# Generated by Django 4.2.7 on 2024-01-16 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_rename_note_content_notemodel_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notemodel',
            name='content',
            field=models.CharField(max_length=255),
        ),
    ]
