# Generated by Django 4.2.7 on 2024-01-18 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_notemodel_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardmodel',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notemodel',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='passwordmodel',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
